# create_k3s_other_master_node.yml
- name: Create Other Master Node
  hosts: localhost
  gather_facts: false
  vars:
    node_name: "{{ node_name }}"
    master_node_ip_address: "{{ master_node_ip_address }}"
    k3s_token: "{{ k3s_token }}"  # Set your K3S token here
    dest_file: "{{ destination_file }}"
    destination_folder: "/opt/k3s/" #"/home/{{username}}/" #"/opt/k3s/}"
    node_ip: "{{node_ip}}"

  tasks:

    - name: Create more variables
      set_fact:
        source_file: "/opt/k3s/{{ dest_file }}"

    - name: 1. Execute k3s_node_maker.j2 template for OTHER_MASTER_NODE - {{ source_file }}
      template:
        src: ../templates/k3s_node_maker.j2
        dest: "{{ source_file }}"
      vars:
        node_type: "{{ node_type }}"
        node_name: "{{ node_name }}"
        node_ip: "{{node_ip}}"
        master_node_ip_address: "{{ master_node_ip_address }}"
        k3s_token: "{{ k3s_token }}"

    - name: 2. Change file permissions of other_master_node.sh - {{ source_file }}
      become: true
      file:
        path: "{{ source_file }}"
        mode: "775"
        owner: "{{ username }}"  # Set the owner here
        group: "{{ username }}"  # Set the group here

    - name: 3. SCP Copy file  {{ source_file }} to {{ username  }}@{{ node_ip}}:{{destination_folder}}
      ansible.builtin.command: >
        sshpass -p "{{ password }}"
        scp -o StrictHostKeyChecking=no -p "{{ source_file }}" "{{ username  }}@{{ node_ip}}:{{destination_folder}}"
      delegate_to: localhost
