# playbooks/create_k3s_scripts/create_k3s_second_master_node.yml
- name: Create Second Master Node
  hosts: other_master_nodes
  become: true
  vars_files:
    - ../../vars/other_master_node_variables.yml
  tasks:

    - name: Show variable names and values
      debug:
        msg: "node_name {{ node_name }} node_ip {{ node_ip }} master_node_ip_address {{ master_node_ip_address }} "

    
