- name: 1. Create Primary Master Node
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../../vars/primary_master_node_variables.yml

  tasks:

    - name: 1.1 Display current server name
      debug:
        msg: "Current server name is {{ inventory_hostname }}"


    - name: 1.1b Display current server name
      debug:
        msg: "Current server name is {{ groups['primary_master_node'][0] }}"


    - name: 1.2 Display current server IP
      debug:
        msg: "IP address of the current server is {{ ansible_host }}"


    - name: 1.2b Display current server IP
      debug:
        msg: "IP address of the current server is {{ hostvars[groups['primary_master_node'][0]]['ansible_host'] }}"


    - name: 1.3 Create more variables
      set_fact:
        source_file: "/opt/k3s/{{destination_file}}"
        node_type: "{{node_type}}"
        node_name: '{{ node_name}}'
        node_ip: '{{ node_ip }}'
        master_node_ip_address: '{{ node_ip }}'
        k3s_token: "Not/Required"
        username: "{{username}}"
        password: "{{ password }}"
        destination_folder: "{{destination_folder}}"

    - name: 1.4 Execute k3s_node_maker.j2 template for 1ST_MASTER_NODE - {{ source_file }}
      template:
        src: ../../templates/k3s_node_maker.j2
        dest: "{{ source_file }}"
      vars:
        node_type: "{{ node_type }}"
        node_name: "{{ node_name }}"
        master_node_ip_address: "{{ master_node_ip_address }}"
        k3s_token: "{{ k3s_token }}"
      become: true  # If escalated permissions are needed

    - name: 1.5 Change file permissions of other_master_node.sh - {{ source_file }}
      become: true
      file:
        path: "{{ source_file }}"
        mode: "775"
        owner: "{{ username }}"
        group: "{{ username }}"

    - name: 1.6. SCP Copy file  {{ source_file }} to {{ username }}@{{ master_node_ip_address }}:{{ destination_folder }}
      ansible.builtin.command: >
        sshpass -p "{{ password }}" scp -o StrictHostKeyChecking=no -p "{{ source_file }}" "{{ username }}@{{ master_node_ip_address }}:{{ destination_folder }}"
      delegate_to: localhost
