- name: Destroy Worker Nodes
  hosts: worker_nodes
  tasks:
    - name: Execute K3s Node Destruction
      template:
        src: templates/destroy_k3s_node.j2
        dest: /opt/k3s/destroy_k3s_node.sh
      vars:
        node_type: "WORKER_NODE"
