---
# start_other_master_node_in_k3s_cluster.yml

- name: Execute create_k3s_master_node.sh commands on other_master_nodes as root
  hosts: other_master_nodes
  become: true
  tasks:
    - name: Run commands from create_k3s_master_node.sh
      shell: "bash /opt/k3s/create_k3s_master_node.sh"
